valore_1 , valore_2 = input("passami il primo valore: "),input("passami il secondo valore: ")
v1=int(valore_1)
v2=int(valore_2)
print("la somma è", v1+v2)
print("la somma è", int(valore_1) + int(valore_2))
